steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta','compute','instances','create','my-instance','--zone','europe-west3-a','--source-machine-image','batch-gateway-pre-prod-west3-a-latest','--subnet=projects/groupama-host-network/regions/europe-west1/subnetworks/nexus-pre-prod-recovery-subnet',
  '--no-address' ]